#!/bin/sh
osascript -e 'quit app "Karabiner-Elements"'
(
    cd ~/.config/karabiner
    rm karabiner.json
    ln -s karabiner_mbjis.json karabiner.json
)
open /Applications/Karabiner-Elements.app
osascript -e 'quit app "Karabiner-Elements"'
